In [2]:
import pandas as pd

In [4]:
df  = pd.read_csv("sorted_data.csv")

In [5]:
df

   id          name   age country   gender   income
0   9   Carlos Ruiz   NaN  Mexico     Male  45000.0
1   3          Alex   NaN     USA  Unknown  47000.0
2   5        Li Wei  27.0   China     Male  51000.0
3   1      John Doe  29.0     USA     Male  55000.0
4  10   Emily Davis  31.0     USA      NaN  58000.0
5   2    Jane Smith   NaN  Canada   Female  62000.0
6   8    Rachel Lee  29.0     USA   Female  62000.0
7   7    Ahmed Khan  38.0     NaN     Male  68000.0
8   6           NaN  45.0   India   Female  73000.0
9   4  Maria Garcia  34.0   Spain   Female      NaN

In [7]:
melted  = pd.melt(df,id_vars=["id","name"],value_vars=["income","gender"],var_name="Meleted",value_name="Values")
print(melted)

    id          name Meleted   Values
0    9   Carlos Ruiz  income  45000.0
1    3          Alex  income  47000.0
2    5        Li Wei  income  51000.0
3    1      John Doe  income  55000.0
4   10   Emily Davis  income  58000.0
5    2    Jane Smith  income  62000.0
6    8    Rachel Lee  income  62000.0
7    7    Ahmed Khan  income  68000.0
8    6           NaN  income  73000.0
9    4  Maria Garcia  income      NaN
10   9   Carlos Ruiz  gender     Male
11   3          Alex  gender  Unknown
12   5        Li Wei  gender     Male
13   1      John Doe  gender     Male
14  10   Emily Davis  gender      NaN
15   2    Jane Smith  gender   Female
16   8    Rachel Lee  gender   Female
17   7    Ahmed Khan  gender     Male
18   6           NaN  gender   Female
19   4  Maria Garcia  gender   Female

In [13]:
reverted = pd.pivot(melted,index=["id","name"],columns="Meleted",values="Values")
print(reverted)
print(df)
reverted.reset_index()

Meleted           gender   income
id name
1  John Doe         Male  55000.0
2  Jane Smith     Female  62000.0
3  Alex          Unknown  47000.0
4  Maria Garcia   Female      NaN
5  Li Wei           Male  51000.0
6  NaN            Female  73000.0
7  Ahmed Khan       Male  68000.0
8  Rachel Lee     Female  62000.0
9  Carlos Ruiz      Male  45000.0
10 Emily Davis       NaN  58000.0
   id          name   age country   gender   income
0   9   Carlos Ruiz   NaN  Mexico     Male  45000.0
1   3          Alex   NaN     USA  Unknown  47000.0
2   5        Li Wei  27.0   China     Male  51000.0
3   1      John Doe  29.0     USA     Male  55000.0
4  10   Emily Davis  31.0     USA      NaN  58000.0
5   2    Jane Smith   NaN  Canada   Female  62000.0
6   8    Rachel Lee  29.0     USA   Female  62000.0
7   7    Ahmed Khan  38.0     NaN     Male  68000.0
8   6           NaN  45.0   India   Female  73000.0
9   4  Maria Garcia  34.0   Spain   Female      NaN

Meleted  id          name   gender   income
0         1      John Doe     Male  55000.0
1         2    Jane Smith   Female  62000.0
2         3          Alex  Unknown  47000.0
3         4  Maria Garcia   Female      NaN
4         5        Li Wei     Male  51000.0
5         6           NaN   Female  73000.0
6         7    Ahmed Khan     Male  68000.0
7         8    Rachel Lee   Female  62000.0
8         9   Carlos Ruiz     Male  45000.0
9        10   Emily Davis      NaN  58000.0