In [1]:
import pandas as pd
d = pd.read_csv("raw_data.csv")

In [2]:
d

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [3]:
d.isnull()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [4]:
d.isna()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [5]:
d.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [6]:
d.dropna()

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [7]:
d.dropna(axis = 1)

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [8]:
print(d.fillna(100))

    id          name    age country   gender   income
0    1      John Doe   29.0     USA     Male  55000.0
1    1      John Doe   29.0     USA     Male  55000.0
2    2    Jane Smith  100.0  Canada   Female  62000.0
3    3          Alex  100.0     USA  Unknown  47000.0
4    4  Maria Garcia   34.0   Spain   Female    100.0
5    5        Li Wei   27.0   China     Male  51000.0
6    6           100   45.0   India   Female  73000.0
7    7    Ahmed Khan   38.0     100     Male  68000.0
8    8    Rachel Lee   29.0     USA   Female  62000.0
9    9   Carlos Ruiz  100.0  Mexico     Male  45000.0
10  10   Emily Davis   31.0     USA      100  58000.0

In [9]:
age_mean = d["age"].mean()

filled_age = (d["age"].copy()).fillna(age_mean)
print(filled_age)

0     29.00
1     29.00
2     32.75
3     32.75
4     34.00
5     27.00
6     45.00
7     38.00
8     29.00
9     32.75
10    31.00
Name: age, dtype: float64

In [10]:
print(d["age"].ffill())

0     29.0
1     29.0
2     29.0
3     29.0
4     34.0
5     27.0
6     45.0
7     38.0
8     29.0
9     29.0
10    31.0
Name: age, dtype: float64

In [11]:
print(d["age"].bfill())

0     29.0
1     29.0
2     34.0
3     34.0
4     34.0
5     27.0
6     45.0
7     38.0
8     29.0
9     31.0
10    31.0
Name: age, dtype: float64