In [1]:
import pandas as pd

In [2]:
d = pd.read_csv("raw_data.csv")

In [3]:
# 1. apply(function)

# A new column will be added
d["tax"] = d["income"].apply(lambda x : "20%" if x>=50000 else "10%")

print(d)
def func(x):
    return ("True" if int(x)>=50000 else "False")
d["income"]=d["income"].ffill()
d["income"] = d["income"].apply(func)
print(d)

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
1    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%
    id          name   age country   gender income  tax
0    1      John Doe  29.0     USA     Male   True  20%
1    1      John Doe  29.0     USA     Male   True  20%
2    2    Jane Smith   NaN  Canada   Female   True  20%
3    3          Alex   NaN     USA  Unknown  False  10%
4    4  Maria Garcia  34.0   Spain   Female  False  10%
5    5        Li Wei  27.0   China     Male   True  20%
6    6           NaN  45.0   India   Female   True  20%
7    7    Ahmed Khan  38.0     NaN     Male   True  20%
8    8    Rachel Lee  29.0     USA   Female   True  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  False  10%
10  10   Emily Davis  31.0     USA      NaN   True  20%

In [4]:
# map function :
dic={
    "True" : "T",
    "False" : "F"
}
d["income"] = d["income"].map(dic)

print(d)

    id          name   age country   gender income  tax
0    1      John Doe  29.0     USA     Male      T  20%
1    1      John Doe  29.0     USA     Male      T  20%
2    2    Jane Smith   NaN  Canada   Female      T  20%
3    3          Alex   NaN     USA  Unknown      F  10%
4    4  Maria Garcia  34.0   Spain   Female      F  10%
5    5        Li Wei  27.0   China     Male      T  20%
6    6           NaN  45.0   India   Female      T  20%
7    7    Ahmed Khan  38.0     NaN     Male      T  20%
8    8    Rachel Lee  29.0     USA   Female      T  20%
9    9   Carlos Ruiz   NaN  Mexico     Male      F  10%
10  10   Emily Davis  31.0     USA      NaN      T  20%

In [5]:
# 3] Assign Function : Creates a new column.

d = d.assign(new_age  = d["age"]*2)
print(d)

    id          name   age country   gender income  tax  new_age
0    1      John Doe  29.0     USA     Male      T  20%     58.0
1    1      John Doe  29.0     USA     Male      T  20%     58.0
2    2    Jane Smith   NaN  Canada   Female      T  20%      NaN
3    3          Alex   NaN     USA  Unknown      F  10%      NaN
4    4  Maria Garcia  34.0   Spain   Female      F  10%     68.0
5    5        Li Wei  27.0   China     Male      T  20%     54.0
6    6           NaN  45.0   India   Female      T  20%     90.0
7    7    Ahmed Khan  38.0     NaN     Male      T  20%     76.0
8    8    Rachel Lee  29.0     USA   Female      T  20%     58.0
9    9   Carlos Ruiz   NaN  Mexico     Male      F  10%      NaN
10  10   Emily Davis  31.0     USA      NaN      T  20%     62.0

In [6]:
# 4] d.repalce(old,new)

d["name"] =  d["name"].replace("Alex","alooo")
print(d)

    id          name   age country   gender income  tax  new_age
0    1      John Doe  29.0     USA     Male      T  20%     58.0
1    1      John Doe  29.0     USA     Male      T  20%     58.0
2    2    Jane Smith   NaN  Canada   Female      T  20%      NaN
3    3         alooo   NaN     USA  Unknown      F  10%      NaN
4    4  Maria Garcia  34.0   Spain   Female      F  10%     68.0
5    5        Li Wei  27.0   China     Male      T  20%     54.0
6    6           NaN  45.0   India   Female      T  20%     90.0
7    7    Ahmed Khan  38.0     NaN     Male      T  20%     76.0
8    8    Rachel Lee  29.0     USA   Female      T  20%     58.0
9    9   Carlos Ruiz   NaN  Mexico     Male      F  10%      NaN
10  10   Emily Davis  31.0     USA      NaN      T  20%     62.0

In [7]:
d.columns = ["A","B","C","D","E","F","G","H"]
print(d)

     A             B     C       D        E  F    G     H
0    1      John Doe  29.0     USA     Male  T  20%  58.0
1    1      John Doe  29.0     USA     Male  T  20%  58.0
2    2    Jane Smith   NaN  Canada   Female  T  20%   NaN
3    3         alooo   NaN     USA  Unknown  F  10%   NaN
4    4  Maria Garcia  34.0   Spain   Female  F  10%  68.0
5    5        Li Wei  27.0   China     Male  T  20%  54.0
6    6           NaN  45.0   India   Female  T  20%  90.0
7    7    Ahmed Khan  38.0     NaN     Male  T  20%  76.0
8    8    Rachel Lee  29.0     USA   Female  T  20%  58.0
9    9   Carlos Ruiz   NaN  Mexico     Male  F  10%   NaN
10  10   Emily Davis  31.0     USA      NaN  T  20%  62.0

In [8]:
d.rename(columns={"Azzzz" : "zzz"})

     A             B     C       D        E  F    G     H
0    1      John Doe  29.0     USA     Male  T  20%  58.0
1    1      John Doe  29.0     USA     Male  T  20%  58.0
2    2    Jane Smith   NaN  Canada   Female  T  20%   NaN
3    3         alooo   NaN     USA  Unknown  F  10%   NaN
4    4  Maria Garcia  34.0   Spain   Female  F  10%  68.0
5    5        Li Wei  27.0   China     Male  T  20%  54.0
6    6           NaN  45.0   India   Female  T  20%  90.0
7    7    Ahmed Khan  38.0     NaN     Male  T  20%  76.0
8    8    Rachel Lee  29.0     USA   Female  T  20%  58.0
9    9   Carlos Ruiz   NaN  Mexico     Male  F  10%   NaN
10  10   Emily Davis  31.0     USA      NaN  T  20%  62.0

In [9]:
d.rename(index={1 : "Faaaah"})

         A             B     C       D        E  F    G     H
0        1      John Doe  29.0     USA     Male  T  20%  58.0
Faaaah   1      John Doe  29.0     USA     Male  T  20%  58.0
2        2    Jane Smith   NaN  Canada   Female  T  20%   NaN
3        3         alooo   NaN     USA  Unknown  F  10%   NaN
4        4  Maria Garcia  34.0   Spain   Female  F  10%  68.0
5        5        Li Wei  27.0   China     Male  T  20%  54.0
6        6           NaN  45.0   India   Female  T  20%  90.0
7        7    Ahmed Khan  38.0     NaN     Male  T  20%  76.0
8        8    Rachel Lee  29.0     USA   Female  T  20%  58.0
9        9   Carlos Ruiz   NaN  Mexico     Male  F  10%   NaN
10      10   Emily Davis  31.0     USA      NaN  T  20%  62.0

In [10]:
print(d["C"].sort_values())
print(d.sort_values("C",ascending = False))
print(d.sort_values(["C","H"]))

5     27.0
0     29.0
1     29.0
8     29.0
10    31.0
4     34.0
7     38.0
6     45.0
2      NaN
3      NaN
9      NaN
Name: C, dtype: float64
     A             B     C       D        E  F    G     H
6    6           NaN  45.0   India   Female  T  20%  90.0
7    7    Ahmed Khan  38.0     NaN     Male  T  20%  76.0
4    4  Maria Garcia  34.0   Spain   Female  F  10%  68.0
10  10   Emily Davis  31.0     USA      NaN  T  20%  62.0
0    1      John Doe  29.0     USA     Male  T  20%  58.0
1    1      John Doe  29.0     USA     Male  T  20%  58.0
8    8    Rachel Lee  29.0     USA   Female  T  20%  58.0
5    5        Li Wei  27.0   China     Male  T  20%  54.0
2    2    Jane Smith   NaN  Canada   Female  T  20%   NaN
3    3         alooo   NaN     USA  Unknown  F  10%   NaN
9    9   Carlos Ruiz   NaN  Mexico     Male  F  10%   NaN
     A             B     C       D        E  F    G     H
5    5        Li Wei  27.0   China     Male  T  20%  54.0
0    1      John Doe  29.0     USA     Male  T  20%  58.0
1    1      John Doe  29.0     USA     Male  T  20%  58.0
8    8    Rachel Lee  29.0     USA   Female  T  20%  58.0
10  10   Emily Davis  31.0     USA      NaN  T  20%  62.0
4    4  Maria Garcia  34.0   Spain   Female  F  10%  68.0
7    7    Ahmed Khan  38.0     NaN     Male  T  20%  76.0
6    6           NaN  45.0   India   Female  T  20%  90.0
2    2    Jane Smith   NaN  Canada   Female  T  20%   NaN
3    3         alooo   NaN     USA  Unknown  F  10%   NaN
9    9   Carlos Ruiz   NaN  Mexico     Male  F  10%   NaN

In [11]:
dc=d.sort_values(["C","H"])
print(dc)

print(dc.sort_index())

     A             B     C       D        E  F    G     H
5    5        Li Wei  27.0   China     Male  T  20%  54.0
0    1      John Doe  29.0     USA     Male  T  20%  58.0
1    1      John Doe  29.0     USA     Male  T  20%  58.0
8    8    Rachel Lee  29.0     USA   Female  T  20%  58.0
10  10   Emily Davis  31.0     USA      NaN  T  20%  62.0
4    4  Maria Garcia  34.0   Spain   Female  F  10%  68.0
7    7    Ahmed Khan  38.0     NaN     Male  T  20%  76.0
6    6           NaN  45.0   India   Female  T  20%  90.0
2    2    Jane Smith   NaN  Canada   Female  T  20%   NaN
3    3         alooo   NaN     USA  Unknown  F  10%   NaN
9    9   Carlos Ruiz   NaN  Mexico     Male  F  10%   NaN
     A             B     C       D        E  F    G     H
0    1      John Doe  29.0     USA     Male  T  20%  58.0
1    1      John Doe  29.0     USA     Male  T  20%  58.0
2    2    Jane Smith   NaN  Canada   Female  T  20%   NaN
3    3         alooo   NaN     USA  Unknown  F  10%   NaN
4    4  Maria Garcia  34.0   Spain   Female  F  10%  68.0
5    5        Li Wei  27.0   China     Male  T  20%  54.0
6    6           NaN  45.0   India   Female  T  20%  90.0
7    7    Ahmed Khan  38.0     NaN     Male  T  20%  76.0
8    8    Rachel Lee  29.0     USA   Female  T  20%  58.0
9    9   Carlos Ruiz   NaN  Mexico     Male  F  10%   NaN
10  10   Emily Davis  31.0     USA      NaN  T  20%  62.0

In [12]:
# Reset Index :

dc = dc.sort_values("H")
print(dc)

# dc = dc.reset_index() # Will print a old index column
# print(dc)

dc.reset_index(drop = True,inplace = True)
print(dc)

     A             B     C       D        E  F    G     H
5    5        Li Wei  27.0   China     Male  T  20%  54.0
0    1      John Doe  29.0     USA     Male  T  20%  58.0
1    1      John Doe  29.0     USA     Male  T  20%  58.0
8    8    Rachel Lee  29.0     USA   Female  T  20%  58.0
10  10   Emily Davis  31.0     USA      NaN  T  20%  62.0
4    4  Maria Garcia  34.0   Spain   Female  F  10%  68.0
7    7    Ahmed Khan  38.0     NaN     Male  T  20%  76.0
6    6           NaN  45.0   India   Female  T  20%  90.0
2    2    Jane Smith   NaN  Canada   Female  T  20%   NaN
3    3         alooo   NaN     USA  Unknown  F  10%   NaN
9    9   Carlos Ruiz   NaN  Mexico     Male  F  10%   NaN
     A             B     C       D        E  F    G     H
0    5        Li Wei  27.0   China     Male  T  20%  54.0
1    1      John Doe  29.0     USA     Male  T  20%  58.0
2    1      John Doe  29.0     USA     Male  T  20%  58.0
3    8    Rachel Lee  29.0     USA   Female  T  20%  58.0
4   10   Emily Davis  31.0     USA      NaN  T  20%  62.0
5    4  Maria Garcia  34.0   Spain   Female  F  10%  68.0
6    7    Ahmed Khan  38.0     NaN     Male  T  20%  76.0
7    6           NaN  45.0   India   Female  T  20%  90.0
8    2    Jane Smith   NaN  Canada   Female  T  20%   NaN
9    3         alooo   NaN     USA  Unknown  F  10%   NaN
10   9   Carlos Ruiz   NaN  Mexico     Male  F  10%   NaN

In [19]:
n = pd.read_csv("raw_data.csv")
print(n)

n["rank"] = n["income"].rank()
print(n)



n["rank"] = n["income"].rank(ascending = False,method = "dense")
print(n)

n["rank"] = n["income"].rank(ascending = False,method = "min")
print(n)

n["rank"] = n["income"].rank(ascending = False,method = "max")
print(n)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0
    id          name   age country   gender   income  rank
0    1      John Doe  29.0     USA     Male  55000.0   4.5
1    1      John Doe  29.0     USA     Male  55000.0   4.5
2    2    Jane Smith   NaN  Canada   Female  62000.0   7.5
3    3          Alex   NaN     USA  Unknown  47000.0   2.0
4    4  Maria Garcia  34.0   Spain   Female      NaN   NaN
5    5        Li Wei  27.0   China     Male  51000.0   3.0
6    6           NaN  45.0   India   Female  73000.0  10.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0   9.0
8    8    Rachel Lee  29.0     USA   Female  62000.0   7.5
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0   1.0
10  10   Emily Davis  31.0     USA      NaN  58000.0   6.0
    id          name   age country   gender   income  rank
0    1      John Doe  29.0     USA     Male  55000.0   5.0
1    1      John Doe  29.0     USA     Male  55000.0   5.0
2    2    Jane Smith   NaN  Canada   Female  62000.0   3.0
3    3          Alex   NaN     USA  Unknown  47000.0   7.0
4    4  Maria Garcia  34.0   Spain   Female      NaN   NaN
5    5        Li Wei  27.0   China     Male  51000.0   6.0
6    6           NaN  45.0   India   Female  73000.0   1.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0   2.0
8    8    Rachel Lee  29.0     USA   Female  62000.0   3.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0   8.0
10  10   Emily Davis  31.0     USA      NaN  58000.0   4.0
    id          name   age country   gender   income  rank
0    1      John Doe  29.0     USA     Male  55000.0   6.0
1    1      John Doe  29.0     USA     Male  55000.0   6.0
2    2    Jane Smith   NaN  Canada   Female  62000.0   3.0
3    3          Alex   NaN     USA  Unknown  47000.0   9.0
4    4  Maria Garcia  34.0   Spain   Female      NaN   NaN
5    5        Li Wei  27.0   China     Male  51000.0   8.0
6    6           NaN  45.0   India   Female  73000.0   1.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0   2.0
8    8    Rachel Lee  29.0     USA   Female  62000.0   3.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10.0
10  10   Emily Davis  31.0     USA      NaN  58000.0   5.0
    id          name   age country   gender   income  rank
0    1      John Doe  29.0     USA     Male  55000.0   7.0
1    1      John Doe  29.0     USA     Male  55000.0   7.0
2    2    Jane Smith   NaN  Canada   Female  62000.0   4.0
3    3          Alex   NaN     USA  Unknown  47000.0   9.0
4    4  Maria Garcia  34.0   Spain   Female      NaN   NaN
5    5        Li Wei  27.0   China     Male  51000.0   8.0
6    6           NaN  45.0   India   Female  73000.0   1.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0   2.0
8    8    Rachel Lee  29.0     USA   Female  62000.0   4.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10.0
10  10   Emily Davis  31.0     USA      NaN  58000.0   5.0

In [21]:
n[["age","id","gender","rank","income","country","name"]]

     age  id   gender  rank   income country          name
0   29.0   1     Male   7.0  55000.0     USA      John Doe
1   29.0   1     Male   7.0  55000.0     USA      John Doe
2    NaN   2   Female   4.0  62000.0  Canada    Jane Smith
3    NaN   3  Unknown   9.0  47000.0     USA          Alex
4   34.0   4   Female   NaN      NaN   Spain  Maria Garcia
5   27.0   5     Male   8.0  51000.0   China        Li Wei
6   45.0   6   Female   1.0  73000.0   India           NaN
7   38.0   7     Male   2.0  68000.0     NaN    Ahmed Khan
8   29.0   8   Female   4.0  62000.0     USA    Rachel Lee
9    NaN   9     Male  10.0  45000.0  Mexico   Carlos Ruiz
10  31.0  10      NaN   5.0  58000.0     USA   Emily Davis