In [1]:
import pandas as pd
d = pd.read_csv("raw_data.csv")

In [5]:
d.groupby("country")["income"].mean()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       55400.0
Name: income, dtype: float64

In [13]:
# Applying Multiple Functions :

print(d.groupby("country")["income"].agg(["mean","max","sum"]))
print(d.groupby("country")["income"].aggregate(["mean","max","sum"]))


# With custom labels :
print(d.groupby("country")["income"].agg(avg_mean="mean",min_val="min"))

            mean      max       sum
country
Canada   62000.0  62000.0   62000.0
China    51000.0  51000.0   51000.0
India    73000.0  73000.0   73000.0
Mexico   45000.0  45000.0   45000.0
Spain        NaN      NaN       0.0
USA      55400.0  62000.0  277000.0
            mean      max       sum
country
Canada   62000.0  62000.0   62000.0
China    51000.0  51000.0   51000.0
India    73000.0  73000.0   73000.0
Mexico   45000.0  45000.0   45000.0
Spain        NaN      NaN       0.0
USA      55400.0  62000.0  277000.0
         avg_mean  min_val
country
Canada    62000.0  62000.0
China     51000.0  51000.0
India     73000.0  73000.0
Mexico    45000.0  45000.0
Spain         NaN      NaN
USA       55400.0  47000.0

In [15]:
# Applying diff functions to diff columns ;

d.groupby("country").agg(
    {
        "income":"mean",
        "age":"max"
    }
)

          income   age
country
Canada   62000.0   NaN
China    51000.0  27.0
India    73000.0  45.0
Mexico   45000.0   NaN
Spain        NaN  34.0
USA      55400.0  31.0

In [16]:
# Applying diff functions to diff columns ; (Custom Labels))

d.groupby("country").agg(
    avg_sal = ("income",'mean'),
    new = ("age","max")
)

         avg_sal   new
country
Canada   62000.0   NaN
China    51000.0  27.0
India    73000.0  45.0
Mexico   45000.0   NaN
Spain        NaN  34.0
USA      55400.0  31.0